"""add suspended_at to user

Revision ID: 00157630946a
Revises: 0bb6cf5b4577
Create Date: 2026-04-20 08:59:51.663895

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00157630946a"
down_revision: str | Sequence[str] | None = "0bb6cf5b4577"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "suspended_at")
    # ### end Alembic commands ###
