"""add_user_activity_table

Revision ID: 068583448048
Revises: d9dec40f843c
Create Date: 2026-02-22 17:56:05.135295

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "068583448048"
down_revision: str | Sequence[str] | None = "d9dec40f843c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("details", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_activity_activity_type"),
        "user_activity",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_created_at"),
        "user_activity",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_resource_id"),
        "user_activity",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_resource_type"),
        "user_activity",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_user_id"), "user_activity", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_activity_user_id"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_resource_type"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_resource_id"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_created_at"), table_name="user_activity")
    op.drop_index(op.f("ix_user_activity_activity_type"), table_name="user_activity")
    op.drop_table("user_activity")
    # ### end Alembic commands ###
