"""add is_root_superadmin to user

Revision ID: 12501ac72e9d
Revises: 60f2912856eb
Create Date: 2026-06-09 07:05:08.850745

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12501ac72e9d"
down_revision: str | Sequence[str] | None = "60f2912856eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_root_superadmin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_root_superadmin")
    # ### end Alembic commands ###
