"""add trigram indexes for admin user search

Revision ID: 1d2f7f8c1513
Revises: 00157630946a
Create Date: 2026-04-20 15:47:24.611040

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d2f7f8c1513"
down_revision: str | Sequence[str] | None = "00157630946a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # gin_trgm_ops requires the pg_trgm extension; create it idempotently
    # before the indexes so fresh databases can apply this migration.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_user_email_trgm",
        "user",
        ["email"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_user_first_name_trgm",
        "user",
        ["first_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"first_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_user_last_name_trgm",
        "user",
        ["last_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"last_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_last_name_trgm",
        table_name="user",
        postgresql_using="gin",
        postgresql_ops={"last_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_user_first_name_trgm",
        table_name="user",
        postgresql_using="gin",
        postgresql_ops={"first_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_user_email_trgm",
        table_name="user",
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
