"""add file category

Revision ID: 6e5b2dc655d9
Revises: ca444cf5f69e
Create Date: 2026-06-05 18:52:39.491861

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5b2dc655d9'
down_revision: str | Sequence[str] | None = 'ca444cf5f69e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('category', sa.String(length=40), server_default='general', nullable=False))
    op.create_index(op.f('ix_file_category'), 'file', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_category'), table_name='file')
    op.drop_column('file', 'category')
    # ### end Alembic commands ###
