"""add file table and user avatar_file_id

Revision ID: ac1432d956db
Revises: 1d2f7f8c1513
Create Date: 2026-05-21 03:54:56.795977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac1432d956db"
down_revision: str | Sequence[str] | None = "1d2f7f8c1513"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("public_id", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_file_uploaded_by_id"), "file", ["uploaded_by_id"], unique=False
    )
    op.add_column("user", sa.Column("avatar_file_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_user_avatar_file_id",
        "user",
        "file",
        ["avatar_file_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_avatar_file_id", "user", type_="foreignkey")
    op.drop_column("user", "avatar_file_id")
    op.drop_index(op.f("ix_file_uploaded_by_id"), table_name="file")
    op.drop_table("file")
    # ### end Alembic commands ###
