"""add status_code to user_activity

Revision ID: b0a2abd604d1
Revises: ac1432d956db
Create Date: 2026-06-03 16:44:24.604340

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0a2abd604d1"
down_revision: str | Sequence[str] | None = "ac1432d956db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_activity", sa.Column("status_code", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_activity", "status_code")
    # ### end Alembic commands ###
