"""add support ticket system

Revision ID: ca444cf5f69e
Revises: b0a2abd604d1
Create Date: 2026-06-05 14:55:30.638711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca444cf5f69e"
down_revision: str | Sequence[str] | None = "b0a2abd604d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_ticket",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("assigned_admin_id", sa.Uuid(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_admin_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_support_ticket_status_last_message",
        "support_ticket",
        ["status", "last_message_at"],
        unique=False,
    )
    op.create_index(
        "ix_support_ticket_user_id", "support_ticket", ["user_id"], unique=False
    )
    op.create_table(
        "support_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=True),
        sa.Column("sender_role", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["sender_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["support_ticket.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_support_message_ticket_created",
        "support_message",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "support_message_attachment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["message_id"], ["support_message.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "message_id", "file_id", name="uq_support_attachment_message_file"
        ),
    )
    op.create_index(
        op.f("ix_support_message_attachment_message_id"),
        "support_message_attachment",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_support_message_attachment_message_id"),
        table_name="support_message_attachment",
    )
    op.drop_table("support_message_attachment")
    op.drop_index("ix_support_message_ticket_created", table_name="support_message")
    op.drop_table("support_message")
    op.drop_index("ix_support_ticket_user_id", table_name="support_ticket")
    op.drop_index("ix_support_ticket_status_last_message", table_name="support_ticket")
    op.drop_table("support_ticket")
    # ### end Alembic commands ###
