name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        env:
          PROJECT_NAME: "FastAPI Template Test"
          POSTGRES_SERVER: "localhost"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "changedsasadsadsadasddsathis"
          FIRST_SUPERUSER: "admin@example.com"
          FIRST_SUPERUSER_PASSWORD: "chanasdsadsdasaddsasdagethis"
        run: uv run pytest
